### ISSUE TITLE
About the downloaded i3d feature.

### ISSUE THREAD

**Issue by shyern** [wanboyang/Anomaly_AR_Net_ICME_2020#3]
I have downloaded the i3d features and extracted the features in a local path. I have also changed the "dataset_path" to my local path. But the i3d features still cannot be found. I notice that there is just one file named "dataset" in the extracted file.  Here is the error information:

Traceback (most recent call last):
  File "/data1/haoyue/codes/remote/Anomaly-Detection/Anomaly_AR_Net_ICME_2020/main.py", line 29, in <module>
    train_dataset = dataset(args=args, train=True)
  File "/data1/haoyue/codes/remote/Anomaly-Detection/Anomaly_AR_Net_ICME_2020/video_dataset_anomaly_balance_uni_sample.py", line 38, in __init__
    self.videoname = os.listdir(self.feature_path)
NotADirectoryError: [Errno 20] Not a directory: './dataset/dataset/shanghaitech/features_video/i3d/combine'

**Comment by wanboyang** [comment]
The downloaded zipped feature files should be unzipped.

**Comment by DungVo1507** [comment]
hI @wanboyang,
I am having some difficulty while testing ShanghaiTech, I have downloaded ShanghaiTech's i3d feature but I don't know how to structure it and can you tell me what should I change in options.py?

Looking forward to your help, I'm a newbie in this field!

**Comment by DungVo1507** [comment]
Hi @shyern,
I wonder if you have fixed this error, if you did, can you show me back?
Thanks very much!

**Comment by Smallwhite999** [comment]
> hI @wanboyang, I am having some difficulty while testing ShanghaiTech, I have downloaded ShanghaiTech's i3d feature but I don't know how to structure it and can you tell me what should I change in options.py?
> 
> Looking forward to your help, I'm a newbie in this field!

Did you reproduce successfully? Where are the video_label.pickle and train_split.txt files in the main.py file? I didn't find it. Please let me know. Thank you

**Comment by wanboyang** [comment]
> > hI @wanboyang, I am having some difficulty while testing ShanghaiTech, I have downloaded ShanghaiTech's i3d feature but I don't know how to structure it and can you tell me what should I change in options.py?
> > Looking forward to your help, I'm a newbie in this field!
> 
> Did you reproduce successfully? Where are the video_label.pickle and train_split.txt files in the main.py file? I didn't find it. Please let me know. Thank you

the dataset.tar file can be unzip by using tar -xvf dataset.tar
