### ISSUE TITLE
other data sets features

### ISSUE THREAD

**Issue by Yii-maker** [wanboyang/Anomaly_AR_Net_ICME_2020#4]
Have you experimented on other data sets? Can you provide features, such as UCF, if it is convenient for you.

**Comment by wanboyang** [comment]
For Auenve, ped2, shanghaitech and UCF_Crime, we provide the i3d features in (link: https://pan.baidu.com/s/1fYAlFoTdcg8BgRdqoLQ2Bg pw: njy2) or (link:https://stujxufeeducn-my.sharepoint.com/:f:/g/personal/2201810057_stu_jxufe_edu_cn/EuQvbLCDoIxLgmcgpJRqcbIBzJSc7D6V-q151gLsWyFTrQ?e=JNbUEc pw:123456)
