### ISSUE TITLE
TestResult

### ISSUE THREAD

**Issue by fmandune** [wanboyang/Anomaly_AR_Net_ICME_2020#6]
您好，您的测试数据结果是根据哪次迭代的结果，还是根据最好的那次

**Comment by wanboyang** [comment]
我们选择了次优的测试结果。

**Comment by fmandune** [comment]
FAR和AUC是同一次迭代的效果吗 ？我复现的效果如下与您论文的结果好像对应不上：
device:0
lr:0.0001
model_name:model_single
loss_type:DMIL_C
pretrain:0
pretrained_ckpt:None
testing_path:None
testing_model:None
feature_size:2048
batch_size:1
sample_size:30
sample_step:1
dataset_name:shanghaitech
dataset_path:.\dataset\dataset
feature_modal:combine
max_seqlen:300
Lambda:1_20
seed:1
max_epoch:20
feature_pretrain_model:i3d
feature_layer:fc6
k:4
plot:1
larger_mem:0
snapshot:200
label_type:unary
itration_200_AUC_Score_all_video is 0.9128746011232162
itration_200_AUC_Score_abnormal_video is 0.6509099311572282
itration_200_ano_false_alarm_all_video is 0.021559397724872514
itration_200_ano_false_alarm_normal_video is 0.004674110620618021
itration_200_ano_false_alarm_abnormal_video is 0.24453493356193742
itration_400_AUC_Score_all_video is 0.9251868607127879
itration_400_AUC_Score_abnormal_video is 0.6498719613932311
itration_400_ano_false_alarm_all_video is 0.01590929664162216
itration_400_ano_false_alarm_normal_video is 0.0019475460919241756
itration_400_ano_false_alarm_abnormal_video is 0.20027861123017573
itration_600_AUC_Score_all_video is 0.9325610740690881
itration_600_AUC_Score_abnormal_video is 0.6604650026727397
itration_600_ano_false_alarm_all_video is 0.01540388038984943
itration_600_ano_false_alarm_normal_video is 0.001817709685795897
itration_600_ano_false_alarm_abnormal_video is 0.19481354479211316
itration_800_AUC_Score_all_video is 0.9332857090708395
itration_800_AUC_Score_abnormal_video is 0.6652482665018712
itration_800_ano_false_alarm_all_video is 0.018428834374339943
itration_800_ano_false_alarm_normal_video is 0.0025967281225655675
itration_800_ano_false_alarm_abnormal_video is 0.22749678525503644
itration_1000_AUC_Score_all_video is 0.9334655668197936
itration_1000_AUC_Score_abnormal_video is 0.6671376654412917
itration_1000_ano_false_alarm_all_video is 0.01860987900184062
itration_1000_ano_false_alarm_normal_video is 0.0027265645286938455
itration_1000_ano_false_alarm_abnormal_video is 0.2283540505786541
itration_1200_AUC_Score_all_video is 0.9337677187082021
itration_1200_AUC_Score_abnormal_video is 0.6690071782461251
itration_1200_ano_false_alarm_all_video is 0.018315681482152017
itration_1200_ano_false_alarm_normal_video is 0.0027265645286938455
itration_1200_ano_false_alarm_abnormal_video is 0.224174882126018
itration_1400_AUC_Score_all_video is 0.9325247905832691
itration_1400_AUC_Score_abnormal_video is 0.6669056245121683
itration_1400_ano_false_alarm_all_video is 0.0187909236293413
itration_1400_ano_false_alarm_normal_video is 0.0029862373409504026
itration_1400_ano_false_alarm_abnormal_video is 0.22749678525503644
itration_1600_AUC_Score_all_video is 0.931262743062265
itration_1600_AUC_Score_abnormal_video is 0.6635189293305138
itration_1600_ano_false_alarm_all_video is 0.01698047735433451
itration_1600_ano_false_alarm_normal_video is 0.0023370553103090105
itration_1600_ano_false_alarm_abnormal_video is 0.21035147878268323
itration_1800_AUC_Score_all_video is 0.930689138355543
itration_1800_AUC_Score_abnormal_video is 0.663056468624543
itration_1800_ano_false_alarm_all_video is 0.016082797742976978
itration_1800_ano_false_alarm_normal_video is 0.0022072189041807324
itration_1800_ano_false_alarm_abnormal_video is 0.19931418774110587
itration_2000_AUC_Score_all_video is 0.928887243692627
itration_2000_AUC_Score_abnormal_video is 0.6581078472632463
itration_2000_ano_false_alarm_all_video is 0.016444886997978334
itration_2000_ano_false_alarm_normal_video is 0.0022072189041807324
itration_2000_ano_false_alarm_abnormal_video is 0.20445777968281184
itration_2200_AUC_Score_all_video is 0.9283447793313562
itration_2200_AUC_Score_abnormal_video is 0.6601827060230563
itration_2200_ano_false_alarm_all_video is 0.01836848616517305
itration_2200_ano_false_alarm_normal_video is 0.0027265645286938455
itration_2200_ano_false_alarm_abnormal_video is 0.22492498928418345
itration_2400_AUC_Score_all_video is 0.9296311882953446
itration_2400_AUC_Score_abnormal_video is 0.6642948128098698
itration_2400_ano_false_alarm_all_video is 0.021996922241332487
itration_2400_ano_false_alarm_normal_video is 0.00402492858997663
itration_2400_ano_false_alarm_abnormal_video is 0.25932276039434204
itration_2600_AUC_Score_all_video is 0.929125532385404
itration_2600_AUC_Score_abnormal_video is 0.6641411275740926
itration_2600_ano_false_alarm_all_video is 0.01921336109350955
itration_2600_ano_false_alarm_normal_video is 0.003116073747078681
itration_2600_ano_false_alarm_abnormal_video is 0.23178311187312473
itration_2800_AUC_Score_all_video is 0.9277024497918801
itration_2800_AUC_Score_abnormal_video is 0.658504705340443
itration_2800_ano_false_alarm_all_video is 0.018006396910171692
itration_2800_ano_false_alarm_normal_video is 0.0027265645286938455
itration_2800_ano_false_alarm_abnormal_video is 0.2197813973424775
itration_3000_AUC_Score_all_video is 0.9272285048420764
itration_3000_AUC_Score_abnormal_video is 0.6601684398830263
itration_3000_ano_false_alarm_all_video is 0.01945475393017712
itration_3000_ano_false_alarm_normal_video is 0.003116073747078681
itration_3000_ano_false_alarm_abnormal_video is 0.23521217316759538
itration_3200_AUC_Score_all_video is 0.9264206666109442
itration_3200_AUC_Score_abnormal_video is 0.6600032985044978
itration_3200_ano_false_alarm_all_video is 0.017712199390483088
itration_3200_ano_false_alarm_normal_video is 0.0025967281225655675
itration_3200_ano_false_alarm_abnormal_video is 0.21731675953707671
itration_3400_AUC_Score_all_video is 0.9271081279679667
itration_3400_AUC_Score_abnormal_video is 0.661370037950094
itration_3400_ano_false_alarm_all_video is 0.025180290274886094
itration_3400_ano_false_alarm_normal_video is 0.00558296546351597
itration_3400_ano_false_alarm_abnormal_video is 0.28396913844834976
itration_3600_AUC_Score_all_video is 0.9245630647383056
itration_3600_AUC_Score_abnormal_video is 0.6553659383802182
itration_3600_ano_false_alarm_all_video is 0.019847017289761928
itration_3600_ano_false_alarm_normal_video is 0.0033757465593352376
itration_3600_ano_false_alarm_abnormal_video is 0.23735533647663953
itration_3800_AUC_Score_all_video is 0.9266994765546067
itration_3800_AUC_Score_abnormal_video is 0.6610600736348979
itration_3800_ano_false_alarm_all_video is 0.01856461784496545
itration_3800_ano_false_alarm_normal_video is 0.0029862373409504026
itration_3800_ano_false_alarm_abnormal_video is 0.2242820402914702
itration_4000_AUC_Score_all_video is 0.9254704333870275
itration_4000_AUC_Score_abnormal_video is 0.655582740477946
itration_4000_ano_false_alarm_all_video is 0.019100208201321626
itration_4000_ano_false_alarm_normal_video is 0.0029862373409504026
itration_4000_ano_false_alarm_abnormal_video is 0.23189027003857693
itration_4200_AUC_Score_all_video is 0.9245655374019438
itration_4200_AUC_Score_abnormal_video is 0.6525551845638635
itration_4200_ano_false_alarm_all_video is 0.019711233819136417
itration_4200_ano_false_alarm_normal_video is 0.0033757465593352376
itration_4200_ano_false_alarm_abnormal_video is 0.23542648949849979
itration_4400_AUC_Score_all_video is 0.9238475139223516
itration_4400_AUC_Score_abnormal_video is 0.6546318806295863
itration_4400_ano_false_alarm_all_video is 0.019085121149029903
itration_4400_ano_false_alarm_normal_video is 0.0029862373409504026
itration_4400_ano_false_alarm_abnormal_video is 0.23167595370767252
itration_4600_AUC_Score_all_video is 0.9232490836727006
itration_4600_AUC_Score_abnormal_video is 0.6518992663529413
itration_4600_ano_false_alarm_all_video is 0.01701819498506382
itration_4600_ano_false_alarm_normal_video is 0.0025967281225655675
itration_4600_ano_false_alarm_abnormal_video is 0.20745820831547365
